name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main  # Ejecuta el workflow automáticamente al hacer push a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release

    - name: Publish application
      run: dotnet publish --configuration Release --output ./published

    - name: Simulate deploy (guardar archivos publicados)
      uses: actions/upload-artifact@v4
      with:
        name: app-publicada
        path: ./published
